crud/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.ListaUsuarios.as_view(), name='index'),
    url(r'^crear/$', views.CrearUsuario.as_view(), name='crear'),
    url(r'^ver/(?P<usuarios_id>[0-9]+)', views.VerUsario.as_view(), name='ver'),
    url(r'^modificar/(?P<pk>[0-9]+)', views.ModificarUsuario.as_view(), name='modificar'),
    url(r'^borrar/(?P<usuario_id>[0-9]+)', views.BorrarUsuario.as_view(), name='borrar'),
]

myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin



urlpatterns = [
    url(r'^usuarios/', include('crud.urls',namespace="usuarios")),
    url(r'^admin/', include(admin.site.urls)),

]

crud/models.py
from django.db import models
# Create your models here.

class Usuarios(models.Model):
    name = models.CharField(max_length=50)
    twitter = models.CharField(max_length=50)

    def __str__(self):
        return self.name

crud/forms.py
from django import forms
from models import Usuarios

class UsuariosForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields =  '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Nombre'}),
            'twitter': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Twitter'})

        }

crud/views.py
from django.shortcuts import render
from .models import Usuarios
from .forms import UsuariosForm
from django.views.generic import CreateView,DetailView, ListView, UpdateView,DeleteView
from django.core.urlresolvers import reverse


# Create your views here.

class ListaUsuarios(ListView):
    model = Usuarios
    template_name = "lista.html"

class CrearUsuario(CreateView):
    model = Usuarios
    form_class = UsuariosForm
    template_name = "crear.html"

    def get_success_url(self):
        return reverse('usuarios:index')

class VerUsario(DetailView):
    pk_url_kwarg ='usuarios_id'
    model = Usuarios
    template_name = "ver.html"

class ModificarUsuario(UpdateView):
    model = Usuarios
    form_class = UsuariosForm
    template_name = "crear.html"

    def get_success_url(self):
        return reverse('usuarios:index')


class BorrarUsuario(DeleteView):
    model = Usuarios
    template_name = ""

crud/templates/base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <title>{% block title %}CRUD en Django{% endblock %}</title>
	<title></title>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

	<style>
		body {
			width: 450px;
			margin: 50px auto;
		}
		.badge {
			float: right;
		}
	</style>
</head>
<body>
	<h1>CRUD en Django</h1>
	<nav class="navbar navbar-default" role="navigation">
  		<div class="container-fluid">
  			<div class="navbar-header">
				<a class="navbar-brand" href="#">Nestor Godoy</a>
  			</div>
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      			<ul class="nav navbar-nav">
        			<li class=""><a href="{% url 'usuarios:index' %}">Todos</a></li>
        			<li class=""><a href="{% url 'usuarios:crear' %}">Nuevo</a></li>
        		</ul>
        	</div>
        </div>
    </nav>

<div class="panel panel-success">
  		<div class="panel-heading">
  			<h4>{% block title1 %}CRUD en Django{% endblock %}</h4>
  		</div>
      		<div class="panel-body">

       {% block content %}{% endblock %}
</div>

</div>


</body>
</html>

crud/templates/crear.html
{% extends "base.html" %}


{% block title %}Lista de usuario{% endblock %}
{% block title1 %}Lista de usuario{% endblock %}

{% block content %}



<Form  action = ""  method = "post" > {%  csrf_token  %}

	<p>		{{ form.name }}    </p>
	<p>    {{ form.twitter }} </p>

	<p><input type="submit" value="Guardar" class="btn btn-success"><p>
</form>


{% endblock %}

crud/templates/lista.html
{% extends "base.html" %}


{% block title %}Lista de usuario{% endblock %}
{% block title1 %}Lista de usuario{% endblock %}

{% block content %}

    		<table class="table">
				<thead>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Twitter</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>


				{% for usuario in object_list %}
						<tr>
							<td>{{ usuario.id }}</td>
							<td>{{ usuario.name }}</td>
							<td>{{ usuario.twitter }}</td>
							<td>
								<a href="{% url 'usuarios:ver'  usuario.id %}"><span class="label label-info">Ver</span></a>
								<a href="{% url 'usuarios:modificar' usuario.id %}"><span class="label label-success">Editar</span></a>
								<a href="{% url 'usuarios:borrar' usuario.id %}"><span class="label label-danger">Eliminar</span></a>
							</td>
						</tr>
				  {% endfor %}
				</tbody>
			</table>

{% endblock %}

crud/templates/ver.html
{% extends "base.html" %}


{% block title %}Ver usuario{% endblock %}
{% block title1 %}Ver de usuario{% endblock %}

{% block content %}



	<p>	Nombre : {{ usuarios.name }}    </p>
	<p> twitter :  {{ usuarios.twitter }} </p>



{% endblock %}